In [44]:
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import sys
mndata = MNIST('./2')


In [45]:
# np.set_printoptions(threshold=sys.maxsize)
# np.set_printoptions(threshold=10)

In [46]:
def f(v): # функция активации
    if(v>0): return 1
    else: return 0

## обучение

In [58]:
a=1 # скорость обучения
b=np.random.rand(1,10) # сдвиг
max_epochs=100 # эпохи обучения
print(b)

[[0.18234356 0.27855649 0.32356931 0.15109719 0.82774366 0.01215647
  0.66972736 0.03167536 0.28861828 0.52379308]]


In [48]:
images_train, labels_train = mndata.load_training()
fist=mndata.process_images_to_numpy(images_train)
ass=mndata.process_labels(labels_train)

In [49]:
y=ass # правильные ответы
x=np.around(fist/255) # нейроны
x=np.hstack((x, np.ones((len(x),1))))
print(x) # 60000x785

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [50]:
w=np.random.rand(784,10) # веса
w=np.vstack((w, b))
print(w) # 785x10

[[0.79725099 0.27841634 0.68622147 ... 0.79952935 0.17341542 0.94859615]
 [0.0218462  0.54261201 0.47762433 ... 0.19546178 0.83412428 0.29986964]
 [0.0415977  0.49905228 0.64501847 ... 0.42889113 0.51573359 0.64246998]
 ...
 [0.03319794 0.43752151 0.02488512 ... 0.85737537 0.1896472  0.12309828]
 [0.82021131 0.01797646 0.12056374 ... 0.505204   0.65062563 0.46139226]
 [0.8018035  0.4847151  0.1904446  ... 0.81181452 0.08961788 0.03228784]]


In [51]:
temp=np.eye(10)
shrek=np.vectorize(f)
for epoch in range(max_epochs):
    y1=x@w # 60000x10
    y1=shrek(y1)
    for i in range(len(x)):
        ei=temp[y[i]]-y1[i]
        Di=a*np.dot(x[i].reshape((785,1)), ei.reshape((1,10))) # 785x10
        w=w+Di

In [52]:
print(w)
y1=x@w # 60000x10
y1=shrek(y1)
np.set_printoptions(threshold=sys.maxsize)
print(y1) # выходные значения
np.set_printoptions(threshold=10)

[[ 7.97250993e-01  2.78416339e-01  6.86221473e-01 ...  7.99529354e-01
   1.73415423e-01  9.48596153e-01]
 [ 2.18462015e-02  5.42612015e-01  4.77624329e-01 ...  1.95461775e-01
   8.34124279e-01  2.99869638e-01]
 [ 4.15976967e-02  4.99052279e-01  6.45018469e-01 ...  4.28891129e-01
   5.15733591e-01  6.42469976e-01]
 ...
 [ 3.31979357e-02  4.37521511e-01  2.48851158e-02 ...  8.57375374e-01
   1.89647200e-01  1.23098277e-01]
 [ 8.20211308e-01  1.79764606e-02  1.20563743e-01 ...  5.05204003e-01
   6.50625627e-01  4.61392265e-01]
 [-1.21366982e+04 -1.70101528e+03 -7.61230956e+03 ... -1.64268819e+03
  -2.34234104e+04 -1.35369677e+04]]
[[0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0

## тестовая выборка

In [53]:
images_test, labels_test = mndata.load_testing()
fist=mndata.process_images_to_numpy(images_test)
ass=mndata.process_labels(labels_test)

In [54]:
y=ass
x=np.around(fist/255)
x=np.hstack((x, np.ones((len(x),1))))
print(x) # 10000x785

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [55]:
y1=x@w
y1=shrek(y1)

In [56]:
def predict(vector):
    result=0
    for i in range(10):
        if(vector[i]==1): result=i
    return result

In [57]:
right=0
for i in range(len(x)):
    if(predict(y1[i])==y[i]): right+=1

accyracy=right/10000
print(accyracy) # сколько правильных ответов

0.706
