In [67]:
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import sys
mndata = MNIST('./2')


In [68]:
# np.set_printoptions(threshold=sys.maxsize)
# np.set_printoptions(threshold=10)

In [69]:
def f(v):
    if(v>0): return 1
    else: return 0
# v=u+b
# u=w*x

## обучение

In [70]:
a=1
b=np.random.rand(1,10)
max_epochs=100
print(b)

[[0.19106682 0.85646833 0.64240879 0.78778994 0.37274985 0.84106828
  0.94022032 0.78463619 0.03059171 0.07745051]]


In [71]:
images_train, labels_train = mndata.load_training()
fist=mndata.process_images_to_numpy(images_train)
ass=mndata.process_labels(labels_train)

In [72]:
y=ass
x=np.around(fist/255)
x=np.hstack((x, np.ones((len(x),1))))
print(x) # 60000x785

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [73]:
w=np.random.rand(784,10)
w=np.vstack((w, b))
print(w) # 785x10

[[0.2430551  0.39033186 0.82682457 ... 0.13167911 0.20434881 0.37383266]
 [0.21713801 0.01563856 0.42000983 ... 0.43493656 0.01660578 0.18568157]
 [0.987789   0.57644864 0.56982862 ... 0.2192813  0.38029491 0.24503243]
 ...
 [0.80784915 0.41407452 0.42431895 ... 0.89437708 0.91355507 0.34272518]
 [0.79427156 0.42620837 0.40397195 ... 0.03335696 0.63537429 0.67588288]
 [0.19106682 0.85646833 0.64240879 ... 0.78463619 0.03059171 0.07745051]]


In [74]:
temp=np.eye(10)
shrek=np.vectorize(f)
for epoch in range(max_epochs):
    y1=x@w # 60000x10
    y1=shrek(y1)
    for i in range(len(x)):
        ei=temp[y[i]]-y1[i]
        Di=a*np.dot(x[i].reshape((785,1)), ei.reshape((1,10))) # 785x10
        w=w+Di

In [75]:
print(w)
y1=x@w # 60000x10
y1=shrek(y1)
np.set_printoptions(threshold=sys.maxsize)
print(y1)
np.set_printoptions(threshold=10)

[[ 2.43055104e-01  3.90331864e-01  8.26824566e-01 ...  1.31679111e-01
   2.04348811e-01  3.73832664e-01]
 [ 2.17138014e-01  1.56385627e-02  4.20009833e-01 ...  4.34936562e-01
   1.66057847e-02  1.85681567e-01]
 [ 9.87789002e-01  5.76448636e-01  5.69828624e-01 ...  2.19281303e-01
   3.80294909e-01  2.45032435e-01]
 ...
 [ 8.07849151e-01  4.14074517e-01  4.24318949e-01 ...  8.94377079e-01
   9.13555065e-01  3.42725178e-01]
 [ 7.94271561e-01  4.26208372e-01  4.03971953e-01 ...  3.33569577e-02
   6.35374294e-01  6.75882877e-01]
 [-2.96188089e+04 -5.61014353e+03 -1.72513576e+04 ... -2.53221536e+03
  -7.79319694e+04 -3.73039225e+04]]
[[0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0

## тестовая выборка

In [76]:
images_test, labels_test = mndata.load_testing()
fist=mndata.process_images_to_numpy(images_test)
ass=mndata.process_labels(labels_test)

In [77]:
y=ass
x=np.around(fist/255)
x=np.hstack((x, np.ones((len(x),1))))
print(x) # 10000x785

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [78]:
y1=x@w
y1=shrek(y1)

In [79]:
def predict(vector):
    result=0
    for i in range(10):
        if(vector[i]==1): result=i
    return result

In [80]:
right=0
for i in range(len(x)):
    if(predict(y1[i])==y[i]): right+=1

accyracy=right/10000
print(accyracy)

0.7096
