In [69]:
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import sys
mndata = MNIST('./2')


In [73]:
# np.set_printoptions(threshold=sys.maxsize)
# np.set_printoptions(threshold=10)

In [74]:
y=np.array([
    [1,0,0,0,0,0,0,0,0,0],
    [0,1,0,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,1,0,0,0,0,0],
    [0,0,0,0,0,1,0,0,0,0],
    [0,0,0,0,0,0,1,0,0,0],
    [0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0,1,0],
    [0,0,0,0,0,0,0,0,0,1]])


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [75]:
def f(v):
    if(v>0): return 1
    else: return 0
# v=u+b
# u=w*x

## обучение

In [82]:
images_train, labels_train = mndata.load_training()
fist=mndata.process_images_to_numpy(images_train)
ass=mndata.process_labels(labels_train)

In [84]:
x=np.around(fist/255)
x=np.hstack((x, np.ones((len(x),1))))
print(x)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
b=np.array([1,1,1,1,1,1,1,1,1,1])
max_epochs=100


In [80]:

w=np.random.rand(784,10)
w=np.vstack((w, b))
print(w)
y1=np.dot(x,w)
shrek=np.vectorize(f)
y1=shrek(y1)
print(y1)

# epoch=0
# for xi in x:
#     y1i=[]
#     ei=[]
#     Di=[]
#     w=w+Di

#     epoch+=1
#     print(f"эпоха {epoch}")
    
    

[[0.82641047 0.08871228 0.28443792 ... 0.49447221 0.10978294 0.35239745]
 [0.87750141 0.49641905 0.93663817 ... 0.75421065 0.98415654 0.55837666]
 [0.46455962 0.13404542 0.73982856 ... 0.90430058 0.79474825 0.9779221 ]
 ...
 [0.97809292 0.5934165  0.79524987 ... 0.6171919  0.93143226 0.09229016]
 [0.28916648 0.5393236  0.74014112 ... 0.67110214 0.73967677 0.90976245]
 [1.         1.         1.         ... 1.         1.         1.        ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


## тестовая выборка

In [ ]:
images_test, labels_test = mndata.load_testing()
fist=mndata.process_images_to_numpy(images_test)
ass=mndata.process_labels(labels_test)

In [ ]:
total=100

In [ ]:
right=1
accyracy=right/total