In [26]:
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import sys
mndata = MNIST('./2')


In [27]:
# np.set_printoptions(threshold=sys.maxsize)
# np.set_printoptions(threshold=10)

In [28]:
def f(v): # функция активации
    if(v>0): return 1
    else: return 0

## обучение

In [29]:
a=1 # скорость обучения
b=np.random.rand(1,10) # сдвиг
max_epochs=10 # эпохи обучения
print(b)

[[0.55776747 0.39650011 0.33498875 0.22223118 0.21008747 0.85890551
  0.46595439 0.32668415 0.97722054 0.67292905]]


In [30]:
images_train, labels_train = mndata.load_training()
fist=mndata.process_images_to_numpy(images_train)
ass=mndata.process_labels(labels_train)

In [31]:
y=ass # правильные ответы
x=np.around(fist/255) # нейроны
x=np.hstack((x, np.ones((len(x),1))))
print(x) # 60000x785

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [32]:
w=np.random.rand(784,10) # веса
w=np.vstack((w, b))
print(w) # 785x10

[[0.3968584  0.47587059 0.19261642 ... 0.31674505 0.04441441 0.84574459]
 [0.4639174  0.47454295 0.17158411 ... 0.62449411 0.37151015 0.91617049]
 [0.64039598 0.31233781 0.76761629 ... 0.37559044 0.86734214 0.58825047]
 ...
 [0.32866269 0.75173692 0.55173813 ... 0.75838235 0.4024087  0.87048581]
 [0.81297777 0.59924182 0.87025467 ... 0.1841717  0.33424137 0.23209092]
 [0.55776747 0.39650011 0.33498875 ... 0.32668415 0.97722054 0.67292905]]


In [33]:
temp=np.eye(10)
shrek=np.vectorize(f)
for epoch in range(max_epochs):

    for i in range(len(x)):
        y1=x[i]@w # 1x10
        y1=shrek(y1)
        ei=temp[y[i]]-y1
        Di=a*np.dot(x[i].reshape((785,1)), ei.reshape((1,10))) # 785x10
        w=w+Di

In [34]:
print(w)
y1=x@w # 60000x10
y1=shrek(y1)
np.set_printoptions(threshold=sys.maxsize)
print(y1) # выходные значения
np.set_printoptions(threshold=10)

[[ 3.96858398e-01  4.75870585e-01  1.92616416e-01 ...  3.16745047e-01
   4.44144091e-02  8.45744595e-01]
 [ 4.63917397e-01  4.74542952e-01  1.71584114e-01 ...  6.24494108e-01
   3.71510153e-01  9.16170489e-01]
 [ 6.40395981e-01  3.12337805e-01  7.67616288e-01 ...  3.75590439e-01
   8.67342138e-01  5.88250470e-01]
 ...
 [ 3.28662686e-01  7.51736924e-01  5.51738127e-01 ...  7.58382354e-01
   4.02408695e-01  8.70485812e-01]
 [ 8.12977771e-01  5.99241825e-01  8.70254674e-01 ...  1.84171703e-01
   3.34241366e-01  2.32090918e-01]
 [-1.25442233e+02 -7.60349989e+00 -6.06650112e+01 ... -1.16733159e+01
  -2.24022779e+02 -9.53270710e+01]]
[[0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0

## тестовая выборка

In [35]:
images_test, labels_test = mndata.load_testing()
fist=mndata.process_images_to_numpy(images_test)
ass=mndata.process_labels(labels_test)

In [36]:
y=ass
x=np.around(fist/255)
x=np.hstack((x, np.ones((len(x),1))))
print(x) # 10000x785

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [37]:
y1=x@w
y1=shrek(y1)

In [38]:
def predict(vector):
    result=0
    for i in range(10):
        if(vector[i]==1): result=i
    return result

In [39]:
right=0
for i in range(len(x)):
    if(predict(y1[i])==y[i]): right+=1

accyracy=right/10000
print(accyracy) # сколько правильных ответов

0.7606
