In [66]:
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import sys
mndata = MNIST('./2')
# from scipy.special import expit


In [67]:
# np.set_printoptions(threshold=sys.maxsize)
# np.set_printoptions(threshold=30)

In [68]:
def sig(v):
    return 1/(1 + np.exp(-v))
    # return expit(v)

def softmax(A):
    expA = np.exp(A-A.max())
    return expA / expA.sum()

nums = np.array([4, 5, 6])

shrek=np.vectorize(sig)
print(shrek(nums))
print(softmax(nums))

[0.98201379 0.99330715 0.99752738]
[0.09003057 0.24472847 0.66524096]


## обучение

In [69]:
a=0.01 # скорость обучения
h=300 # длина скрытого слоя
max_epochs=1 # эпохи обучения

In [70]:
images_train, labels_train = mndata.load_training()
fist=mndata.process_images_to_numpy(images_train)
ass=mndata.process_labels(labels_train)
y=ass # правильные ответы

In [71]:
b1=np.random.rand(1,h) # сдвиг 1 слоя
b2=np.random.rand(1,10) # сдвиг 2 слоя

x=(fist/255) # входные нейроны
# x=np.hstack((x, np.ones((len(x),1))))
print(x)
print(np.shape(x))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(60000, 784)


In [72]:
w1=np.random.normal(0, 0.1, (784,h)) # веса 1 слоя
# w1=np.vstack((w1, b1))
print(w1)
print(np.shape(w1))

w2=np.random.normal(0, 0.1, (h,10)) # веса 2 слоя
# w2=np.vstack((w2, b2))
print(w2)
print(np.shape(w2))

[[ 0.02742697  0.02369591 -0.0357826  ... -0.06168667 -0.05013033
   0.03754351]
 [ 0.08263333  0.0270452   0.21885642 ...  0.24510796  0.0121293
   0.06330918]
 [-0.03271195 -0.00386966 -0.1227616  ...  0.00540225 -0.1664252
  -0.00228239]
 ...
 [ 0.02729138  0.21624566  0.10236131 ... -0.00100595  0.02352503
   0.00625824]
 [ 0.15347432 -0.13346128 -0.0096259  ... -0.02998644 -0.14533817
  -0.01811631]
 [-0.01776167 -0.22927436  0.21296933 ... -0.03356106 -0.04917053
  -0.02298506]]
(784, 300)
[[-0.01686341  0.03882004  0.10470072 ... -0.04171357 -0.10117476
   0.05514721]
 [ 0.04698999  0.00873478  0.05335268 ...  0.11682329  0.15227932
  -0.0842535 ]
 [ 0.00388548 -0.08153118 -0.12338044 ...  0.05019869 -0.09837877
   0.05857186]
 ...
 [-0.02377207  0.08342246 -0.10244243 ... -0.11417029  0.16236815
  -0.01513207]
 [ 0.02369503 -0.08758534  0.00117053 ...  0.03158415  0.0692376
  -0.10899173]
 [ 0.21966764  0.08841071  0.11735284 ... -0.04845711  0.06085805
  -0.00601015]]
(300, 10

In [73]:
temp=np.eye(10)
shrek_sig=np.vectorize(sig)

# i=0
# # print(np.shape(x[0]), np.shape(w1))
# # print(x[i], w1)
# y1_1=x[i]@w1 # (300,)
# # print(np.shape(y1_1))
# # print(y1_1)
# y1_1=shrek_sig(y1_1) # (300,)
# # y1_1=np.hstack((y1_1, np.ones(1))) # (301, 10)
# # print(np.shape(y1_1), np.shape(w2))
# # print(y1_1)
# y1_2=y1_1@w2 # (10,)
# # print(y1_2)
# # print(np.shape(y1_2))
# y1_2=softmax(y1_2)
# # print(np.shape(y1_2))
# # print(y1_2)

# delta2=y1_2-temp[y[0]] # (10,)
# # print(delta2)
# # print(np.shape(delta2))
# dLi_dW2=y1_1.reshape((h,1))@delta2.reshape((1,10)) # (300, 10)
# Ih=np.ones((1,h))
# delta1=(y1_1*(Ih-y1_1))*(delta2@w2.T) # (1, 300)
# # print(delta1)
# # print(np.shape(delta1))
# dLi_dW1=x[i].reshape((784,1))@delta1 # (784, 300)

# print(dLi_dW1)
# print(np.shape(dLi_dW1))
# # print(dLi_dW2)
# # print(np.shape(dLi_dW2))
# w1=w1-(a*dLi_dW1)
# w2=w2-(a*dLi_dW2)

for epoch in range(max_epochs):
    for i in range(len(x)):
        y1_1=x[i]@w1 # (300,)
        y1_1=shrek_sig(y1_1) # (300,)
        # y1_1=np.hstack((y1_1, np.ones(1))) # (301, 10)
        y1_2=y1_1@w2 # (10,)
        y1_2=softmax(y1_2)

        delta2=y1_2-temp[y[i]] # (10,)
        dLi_dW2=y1_1.reshape((h,1))@delta2.reshape((1,10)) # (300, 10)
        Ih=np.ones((1,h))
        delta1=(y1_1*(Ih-y1_1))*(delta2@w2.T) # (1, 300)
        dLi_dW1=x[i].reshape((784,1))@delta1 # (300, 300)

        w1=w1-(a*dLi_dW1)
        w2=w2-(a*dLi_dW2)

In [74]:
y1_1=x@w1 # (300,)
y1_1=shrek_sig(y1_1) # (300,)
y1_2=y1_1@w2 # (10,)
y1_2=softmax(y1_2)
print(y1_2[0:20]) # выходные значения

[[4.57899191e-10 2.45831370e-11 4.62684563e-10 3.65501707e-08
  3.74201815e-13 2.22715464e-07 2.06474739e-11 2.05299455e-10
  1.77780083e-10 2.67081533e-10]
 [5.06247395e-05 2.37031643e-13 3.28606008e-10 2.66832805e-10
  6.11407773e-13 4.54374284e-09 4.46635516e-11 7.00700526e-11
  1.83050778e-10 5.44509326e-10]
 [1.27848012e-11 3.02004597e-11 1.28563860e-09 2.90609020e-09
  1.49855194e-07 6.28392381e-11 5.11414802e-11 2.23365918e-10
  3.01461502e-11 7.39327015e-09]
 [1.43402862e-12 1.12428420e-06 1.66771323e-09 4.99196956e-10
  4.39582344e-11 2.21044462e-10 1.39895975e-11 3.93464549e-11
  2.47073508e-09 3.94149975e-11]
 [6.90517146e-13 1.46944150e-10 6.69801532e-12 1.99766493e-11
  1.04231527e-07 1.01772490e-10 5.08156868e-12 3.15499638e-09
  1.70632939e-09 2.07438093e-06]
 [7.53762518e-10 1.90215279e-12 1.53786237e-06 7.35803047e-10
  3.70872935e-12 3.40156356e-10 1.33312582e-11 1.98412812e-11
  4.75484013e-09 2.03716987e-09]
 [1.75511646e-15 2.26601689e-05 1.30967996e-09 1.36798448e

## тестовая выборка

In [75]:
images_test, labels_test = mndata.load_testing()
fist=mndata.process_images_to_numpy(images_test)
ass=mndata.process_labels(labels_test)

In [76]:
y=ass
x=np.around(fist/255)
# x=np.hstack((x, np.ones((len(x),1))))
print(x) # 10000x785

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [77]:
y1_1=x@w1 # (300,)
y1_1=shrek_sig(y1_1) # (300,)
y1_2=y1_1@w2 # (10,)
y1_2=softmax(y1_2)

In [78]:
def predict(vector):
    return np.argmax(vector)

In [79]:
right=0
for i in range(len(x)):
    if(predict(y1_2[i])==y[i]): right+=1

accyracy=right/10000
print(accyracy) # сколько правильных ответов

0.9164
