In [75]:
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import sys
mndata = MNIST('./2')
# from scipy.special import expit


In [76]:
# np.set_printoptions(threshold=sys.maxsize)
# np.set_printoptions(threshold=30)

In [77]:
def sig(v):
    return 1/(1 + np.exp(-v))
    # return expit(v)

def softmax(A):
    expA = np.exp(A)
    return expA / expA.sum()

nums = np.array([4, 5, 6])

shrek=np.vectorize(sig)
print(shrek(nums))
print(softmax(nums))

[0.98201379 0.99330715 0.99752738]
[0.09003057 0.24472847 0.66524096]


## обучение

In [78]:
a=1 # скорость обучения
h=300 # длина скрытого слоя
max_epochs=1 # эпохи обучения

In [79]:
images_train, labels_train = mndata.load_training()
fist=mndata.process_images_to_numpy(images_train)
ass=mndata.process_labels(labels_train)
y=ass # правильные ответы

In [80]:
b1=np.random.rand(1,h) # сдвиг 1 слоя
b2=np.random.rand(1,10) # сдвиг 2 слоя

x=np.around(fist/255) # входные нейроны
# x=np.hstack((x, np.ones((len(x),1))))
print(x)
print(np.shape(x))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(60000, 784)


In [81]:
w1=np.random.uniform(-0.1, 0.1, (784,h)) # веса 1 слоя
# w1=np.vstack((w1, b1))
print(w1)
print(np.shape(w1))

w2=np.random.uniform(-0.1, 0.1, (h,10)) # веса 2 слоя
# w2=np.vstack((w2, b2))
print(w2)
print(np.shape(w2))

[[-3.42274112e-02  2.57402876e-02 -9.25645674e-02 ...  8.22140658e-03
  -6.94077039e-02  5.49334515e-02]
 [ 3.74019071e-02  6.64826075e-02  5.94324616e-02 ...  8.07308887e-02
   9.34479117e-02 -9.20055332e-03]
 [-8.35258860e-02  9.75823857e-02  5.80039225e-02 ...  7.33556395e-03
  -7.56388823e-02 -6.43407777e-02]
 ...
 [ 9.03250486e-02 -8.23736043e-02  4.24077205e-02 ...  9.89968433e-02
  -2.37904564e-02 -5.73183556e-02]
 [-2.35105752e-02 -9.71315089e-02 -2.36900567e-02 ...  6.53856346e-02
  -7.76855514e-05 -4.26755175e-03]
 [-6.97620598e-02  2.80257955e-02 -1.87664592e-02 ... -1.24265852e-02
   5.25827043e-02 -3.52124445e-02]]
(784, 300)
[[ 0.06279068 -0.09879221 -0.09010476 ...  0.00220828 -0.02849588
   0.04423373]
 [ 0.06983541 -0.01204271 -0.01794332 ...  0.06309107  0.06893823
  -0.03678003]
 [ 0.00343416  0.09627238 -0.07951355 ... -0.02086543  0.08981646
   0.08901257]
 ...
 [-0.03070942  0.02131879 -0.07436102 ...  0.08690139 -0.06609377
   0.03495357]
 [ 0.01077782  0.0670341

In [82]:
temp=np.eye(10)
shrek_sig=np.vectorize(sig)

# i=0
# # print(np.shape(x[0]), np.shape(w1))
# # print(x[i], w1)
# y1_1=x[i]@w1 # (300,)
# # print(np.shape(y1_1))
# # print(y1_1)
# y1_1=shrek_sig(y1_1) # (300,)
# # y1_1=np.hstack((y1_1, np.ones(1))) # (301, 10)
# # print(np.shape(y1_1), np.shape(w2))
# # print(y1_1)
# y1_2=y1_1@w2 # (10,)
# # print(y1_2)
# # print(np.shape(y1_2))
# y1_2=softmax(y1_2)
# # print(np.shape(y1_2))
# # print(y1_2)

# delta2=y1_2-temp[y[0]] # (10,)
# # print(delta2)
# # print(np.shape(delta2))
# dLi_dW2=y1_1.reshape((h,1))@delta2.reshape((1,10)) # (300, 10)
# Ih=np.ones((1,h))
# delta1=(y1_1*(Ih-y1_1))*(delta2@w2.T) # (1, 300)
# # print(delta1)
# # print(np.shape(delta1))
# dLi_dW1=x[i].reshape((784,1))@delta1 # (300, 300)

# # print(dLi_dW1)
# # print(np.shape(dLi_dW1))
# # print(dLi_dW2)
# # print(np.shape(dLi_dW2))
# w1=w1-(a*dLi_dW1)
# w2=w2-(a*dLi_dW2)

for epoch in range(max_epochs):
    for i in range(len(x)):
        y1_1=x[i]@w1 # (300,)
        y1_1=shrek_sig(y1_1) # (300,)
        # y1_1=np.hstack((y1_1, np.ones(1))) # (301, 10)
        y1_2=y1_1@w2 # (10,)
        y1_2=softmax(y1_2)

        delta2=y1_2-temp[y[0]] # (10,)
        dLi_dW2=y1_1.reshape((h,1))@delta2.reshape((1,10)) # (300, 10)
        Ih=np.ones((1,h))
        delta1=(y1_1*(Ih-y1_1))*(delta2@w2.T) # (1, 300)
        dLi_dW1=x[i].reshape((784,1))@delta1 # (300, 300)

        w1=w1-(a*dLi_dW1)
        w2=w2-(a*dLi_dW2)

In [83]:
y1_1=x@w1 # (300,)
y1_1=shrek_sig(y1_1) # (300,)
y1_2=y1_1@w2 # (10,)
y1_2=softmax(y1_2)
print(y1_2[0:20]) # выходные значения

[[2.79830833e-40 3.48826247e-39 7.28531947e-41 1.79245764e-39
  6.92279752e-38 7.60789020e-04 6.26760080e-40 5.98688788e-41
  2.49024907e-43 9.67445736e-41]
 [3.20666305e-40 6.34486802e-39 1.18284710e-40 3.09645880e-39
  7.55076802e-38 2.83275195e-05 9.33970058e-40 9.43968379e-41
  5.06911097e-43 1.25808217e-40]
 [5.65334541e-40 8.89647547e-39 2.33641018e-40 4.62972168e-39
  7.06432501e-38 6.35444835e-07 1.23681042e-39 1.73878381e-40
  1.09419638e-42 1.64536344e-40]
 [5.23218898e-40 7.51455553e-39 1.87756184e-40 4.43432364e-39
  8.40470390e-38 1.21740766e-06 1.18061844e-39 1.61217917e-40
  9.77049401e-43 1.64643838e-40]
 [3.76636738e-40 6.72029424e-39 1.51021800e-40 3.37982405e-39
  7.83426664e-38 5.93047264e-06 1.18991812e-39 1.21805996e-40
  5.76584357e-43 1.28906812e-40]
 [3.78785017e-40 6.69744910e-39 1.49486639e-40 2.87380398e-39
  5.70506172e-38 1.38672875e-05 9.89190257e-40 1.21186194e-40
  6.08444114e-43 1.18882991e-40]
 [5.27749933e-40 6.74843769e-39 1.62651614e-40 3.71040877e

## тестовая выборка

In [84]:
images_test, labels_test = mndata.load_testing()
fist=mndata.process_images_to_numpy(images_test)
ass=mndata.process_labels(labels_test)

In [87]:
y=ass
x=np.around(fist/255)
# x=np.hstack((x, np.ones((len(x),1))))
print(x) # 10000x785

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [89]:
y1_1=x@w1 # (300,)
y1_1=shrek_sig(y1_1) # (300,)
y1_2=y1_1@w2 # (10,)
y1_2=softmax(y1_2)

In [90]:
def predict(vector):
    return np.argmax(vector)

In [91]:
right=0
for i in range(len(x)):
    if(predict(y1_2[i])==y[i]): right+=1

accyracy=right/10000
print(accyracy) # сколько правильных ответов

0.0892
