In [136]:
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import sys
mndata = MNIST('./2')


In [138]:
def sig(v):
    return 1/(1 + np.exp(-v))

def softmax(A):
    expA = np.exp(A-A.max())
    return expA / expA.sum()

nums = np.array([4, 5, 6])

shrek=np.vectorize(sig)
print(shrek(nums))
print(softmax(nums))

[0.98201379 0.99330715 0.99752738]
[0.09003057 0.24472847 0.66524096]


## обучение

In [139]:
a=0.1 # скорость обучения
h=300 # длина скрытого слоя
max_epochs=10 # эпохи обучения

In [140]:
images_train, labels_train = mndata.load_training()
fist=mndata.process_images_to_numpy(images_train)
ass=mndata.process_labels(labels_train)
y=ass # правильные ответы

In [141]:

x=(fist/255) # входные нейроны

print(x)
print(np.shape(x))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(60000, 784)


In [142]:
w1=np.random.normal(0, 0.1, (784,h)) # веса 1 слоя

print(w1)
print(np.shape(w1))

w2=np.random.normal(0, 0.1, (h,10)) # веса 2 слоя

print(w2)
print(np.shape(w2))

[[ 1.89169605e-02 -7.86376772e-02  7.38366239e-02 ... -1.50722913e-01
  -2.28639609e-01 -9.85910820e-03]
 [ 1.22662167e-01 -1.52743943e-02 -7.55379114e-03 ...  1.09013489e-01
   5.65498422e-03 -3.35450156e-02]
 [ 3.70244557e-03 -1.43723181e-01  1.69771635e-01 ...  1.46947347e-04
   4.69122992e-02 -8.44153864e-03]
 ...
 [-5.95344773e-02 -7.14960661e-02  9.20891745e-02 ...  1.48492702e-02
  -9.60650769e-02  6.11614856e-02]
 [-1.44548542e-01  1.31834549e-01 -4.82331187e-02 ... -1.11747040e-01
   1.37902918e-02  2.54332576e-03]
 [ 2.54614973e-02  9.59841060e-02 -4.84016432e-02 ...  1.05861020e-01
   1.27532114e-01 -1.37352432e-01]]
(784, 300)
[[ 0.17045937 -0.13450323  0.08251551 ... -0.06699261 -0.02874721
  -0.12240704]
 [ 0.0159584   0.05931656 -0.04776697 ... -0.00724912  0.12050537
  -0.04469727]
 [-0.03692905 -0.03938285  0.02047117 ...  0.01588685  0.02618571
   0.0732258 ]
 ...
 [ 0.01368755 -0.14527644  0.19302581 ... -0.14497407 -0.09972353
  -0.02877172]
 [ 0.04925678  0.0972296

In [143]:
temp=np.eye(10)
shrek_sig=np.vectorize(sig)



for epoch in range(max_epochs):
    for i in range(len(x)):
        y1_1=x[i]@w1 # (300,)
        y1_1=shrek_sig(y1_1) # (300,)
        y1_2=y1_1@w2 # (10,)
        y1_2=softmax(y1_2)

        delta2=y1_2-temp[y[i]] # (10,)
        dLi_dW2=y1_1.reshape((h,1))@delta2.reshape((1,10)) # (300, 10)
        Ih=np.ones((1,h))
        delta1=(y1_1*(Ih-y1_1))*(delta2@w2.T) # (1, 300)
        dLi_dW1=x[i].reshape((784,1))@delta1 # (784, 300)

        w1=w1-(a*dLi_dW1)
        w2=w2-(a*dLi_dW2)

In [144]:
y1_1=x@w1 # (300,)
y1_1=shrek_sig(y1_1) # (300,)
y1_2=y1_1@w2 # (10,)
y1_2=softmax(y1_2)
print(y1_2[0:20]) # выходные значения

[[1.26252351e-21 4.10002547e-17 1.67398103e-18 5.28957814e-11
  1.47998161e-26 7.91279653e-07 4.76884361e-21 2.59993078e-19
  7.78320162e-21 4.19513010e-20]
 [9.48360529e-07 1.71278075e-19 1.24323424e-15 3.00279702e-21
  7.08855113e-21 7.02440506e-21 6.76937046e-19 8.00034974e-21
  1.62656022e-20 8.35954259e-18]
 [1.68469185e-23 1.55636827e-17 2.20609063e-14 5.40289210e-20
  6.92372190e-09 7.46456801e-23 2.02784492e-22 5.47184828e-17
  7.57915217e-19 2.82327153e-18]
 [1.23454999e-21 9.87912699e-10 2.01320246e-18 2.60492845e-21
  6.45714882e-16 4.28023918e-20 9.71975405e-22 1.66676364e-16
  2.39039721e-19 6.54850782e-20]
 [1.62061695e-22 6.62901511e-20 4.34706732e-21 4.88596465e-17
  1.51383860e-15 1.71183530e-16 3.37621275e-24 1.48530967e-18
  3.79601328e-17 5.85505142e-11]
 [8.44377988e-20 1.55871709e-19 3.14614010e-11 1.26034836e-18
  3.29285343e-18 2.45065813e-18 1.25867592e-20 2.62752623e-19
  1.46336427e-18 3.69988797e-19]
 [2.78936434e-22 9.99309733e-10 2.99973979e-19 9.67173430e

## тестовая выборка

In [145]:
images_test, labels_test = mndata.load_testing()
fist=mndata.process_images_to_numpy(images_test)
ass=mndata.process_labels(labels_test)

In [146]:
y=ass
x=np.around(fist/255)
# x=np.hstack((x, np.ones((len(x),1))))
print(x) # 10000x785

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [147]:
y1_1=x@w1 # (300,)
y1_1=shrek_sig(y1_1) # (300,)
y1_2=y1_1@w2 # (10,)
y1_2=softmax(y1_2)

In [148]:
def predict(vector):
    return np.argmax(vector)

In [149]:
right=0
for i in range(len(x)):
    if(predict(y1_2[i])==y[i]): right+=1

accyracy=right/10000
print(accyracy) # сколько правильных ответов

0.976
