In [43]:
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import sys
mndata = MNIST('./2')


In [44]:
# np.set_printoptions(threshold=sys.maxsize)
# np.set_printoptions(threshold=10)

In [45]:
def f(v): # функция активации
    if(v>0): return 1
    else: return 0

## обучение

In [46]:
a=0.5 # скорость обучения
b=np.random.rand(1,10) # сдвиг
max_epochs=50 # эпохи обучения
print(b)

[[0.46839597 0.19011922 0.01230352 0.23439714 0.54278298 0.24590302
  0.21877395 0.30667283 0.01514079 0.25525377]]


In [47]:
images_train, labels_train = mndata.load_training()
fist=mndata.process_images_to_numpy(images_train)
ass=mndata.process_labels(labels_train)

In [48]:
y=ass # правильные ответы
x=np.around(fist/255) # нейроны
x=np.hstack((x, np.ones((len(x),1))))
print(x) # 60000x785

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [49]:
w1=np.random.rand(784,10) # веса
w1=np.vstack((w1, b))
print(w1) # 785x10

w2=np.random.rand(784,10) # веса
w2=np.vstack((w2, b))
print(w2) # 785x10

[[0.22148089 0.13690448 0.58188191 ... 0.79407223 0.40822366 0.11850556]
 [0.27381606 0.97522597 0.60392874 ... 0.95391819 0.76800892 0.38931269]
 [0.08125836 0.92275582 0.67084431 ... 0.95449235 0.33705287 0.49425174]
 ...
 [0.71550899 0.98189864 0.54433101 ... 0.5408894  0.80171184 0.82852588]
 [0.00101522 0.45623532 0.81526038 ... 0.84703663 0.05108546 0.7862008 ]
 [0.46839597 0.19011922 0.01230352 ... 0.30667283 0.01514079 0.25525377]]


In [50]:
temp=np.eye(10)
shrek=np.vectorize(f)
for epoch in range(max_epochs):

    for i in range(len(x)):
        y1=x[i]@w # 1x10
        y1=shrek(y1)
        ei=temp[y[i]]-y1
        Di=a*np.dot(x[i].reshape((785,1)), ei.reshape((1,10))) # 785x10
        w=w+Di

In [51]:
print(w)
y1=x@w # 60000x10
y1=shrek(y1)
np.set_printoptions(threshold=sys.maxsize)
print(y1) # выходные значения
np.set_printoptions(threshold=10)

[[ 2.21480895e-01  1.36904479e-01  5.81881908e-01 ...  7.94072233e-01
   4.08223659e-01  1.18505558e-01]
 [ 2.73816056e-01  9.75225974e-01  6.03928740e-01 ...  9.53918189e-01
   7.68008921e-01  3.89312694e-01]
 [ 8.12583625e-02  9.22755824e-01  6.70844309e-01 ...  9.54492353e-01
   3.37052868e-01  4.94251738e-01]
 ...
 [ 7.15508989e-01  9.81898643e-01  5.44331015e-01 ...  5.40889397e-01
   8.01711845e-01  8.28525885e-01]
 [ 1.01522210e-03  4.56235323e-01  8.15260376e-01 ...  8.47036635e-01
   5.10854626e-02  7.86200797e-01]
 [-6.35316040e+01 -4.30988078e+00 -2.94876965e+01 ... -6.19332717e+00
  -1.12484859e+02 -4.87447462e+01]]
[[0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0

## тестовая выборка

In [52]:
images_test, labels_test = mndata.load_testing()
fist=mndata.process_images_to_numpy(images_test)
ass=mndata.process_labels(labels_test)

In [53]:
y=ass
x=np.around(fist/255)
x=np.hstack((x, np.ones((len(x),1))))
print(x) # 10000x785

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [54]:
y1=x@w
y1=shrek(y1)

In [55]:
def predict(vector):
    result=0
    for i in range(10):
        if(vector[i]==1): result=i
    return result

In [56]:
right=0
for i in range(len(x)):
    if(predict(y1[i])==y[i]): right+=1

accyracy=right/10000
print(accyracy) # сколько правильных ответов

0.7316
